services:
  api:
    build: .
    env_file:
      - ./.env
    ports:
      - "4000:4000"
    command: ./cmd/api/go-api
    depends_on:
      - db
    networks:
      - backend
    restart: on-failure

  db:
    image: postgres:16.2-alpine3.18
    container_name: db-api
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - backend
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./internal/db/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  postgres-db:

networks:
  backend:
