apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: nuitee-challenge
data:
  DATABASE_NAME: "nuitee"
  DATABASE_USER: "nuitee"
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_SSLMODE: "disable"
  PORT: "4000"
  ENVIRONMENT: "dev"
  LITE_API_URL: "https://api.liteapi.travel/v3.0"


