apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: nuitee-challenge
type: Opaque
stringData:
  DATABASE_PASSWORD: "1234"
  DATABASE_DSN: "postgres://nuitee:1234@postgres-service:5432/nuitee?sslmode=disable"
  LITE_API_KEY: ""
  MAILTRAP_USERNAME: ""
  MAILTRAP_PASSWORD: ""


